### ISSUE TITLE
Логотип репозитория

### ISSUE THREAD

**Issue by lord-alfred** [ZennoHelpers/Snippets#47]
Нужно сделать какой-то симпатичный и приятный логотип для репозитория, чтоб поместить его в самое начало. Небольших размеров, лучше прямоугольный и вытянутый по горизонтали.

Есть исследования, подтверждающие мысль о том, что если в README есть изображения или логотип, то такие репозитории становятся быстрее популярнее за счет привлечения внимания :)

**Comment by Astraport** [comment]
Как вариант 
![snippets](https://user-images.githubusercontent.com/1259709/73121376-7f2e5100-3f8a-11ea-8aac-6cedfb963a03.jpg)

**Comment by ghost** [comment]
> Как вариант

Только "ZENNO" бы не таким тонким шрифтом.

**Comment by lord-alfred** [comment]
А мне наоборот нравится,что шрифт тонкий :) Стильно и красиво, особенно фигурные скобки прям в тему тут 👍 

Единственное что с размерами нужно поиграться, а то я попробовал вставить и как-то криво немного выглядит: https://github.com/lord-alfred/Snippets/tree/readme_img_test

PS: ещё такое чувство что пожато сильно, видны артефакты если увеличить.
PPS: может прозрачный фон лучше будет?

**Comment by Astraport** [comment]
Вариант с более жирным шрифтом PNG32 без фона.
Пережато это Гитхаб виноват, увеличивает картинку. попробуй открыть картинку в новом окне и увидишь, что всё норм.
![snippets](https://user-images.githubusercontent.com/1259709/73122452-3086b400-3f96-11ea-9146-81b02f6407de.png)

**Comment by ghost** [comment]
> Вариант с более жирным шрифтом PNG32 без фона.

Уже получше, можно его, а то можно вечно придираться :)

**Comment by lord-alfred** [comment]
Да, мне тоже кажется что экспериментировать можно вечность :) Давайте на этом варианте остановимся и его используем.

@Astraport , спасибо огромное что взял инициативу в свои руки! Выложи ещё на всякий случай исходник (если остался) и названия шрифтов.

Поменял картинку и чуть уменьшил размер, норм или стоит другой какой-то height задать?
https://github.com/lord-alfred/Snippets/tree/readme_img_test

Ещё можно было бы первый абзац дописать, но я не могу придумать чего ещё там не хватает)

**Comment by Astraport** [comment]
Шрифты Reforma Grotesk Demi и, конечно, Lucida Console.
Исходник могу приложить, но он в довольно экзотическом формате Adobe Fireworks, хотя может и нормально импортится в Фотошоп. 

[snippets.fw.zip](https://github.com/ZennoHelpers/Snippets/files/4112238/snippets.fw.zip)

**Comment by lord-alfred** [comment]
@Astraport ещё раз большое спасибо, что сделал логотип!)

На прошлой неделе замотался и забыл сделать PR, а теперь всё смержено и лого уже красуется в ридми.

Ишью закрываю, если вдруг кто-то в будущем захочет дорисовать или прислать свой вариант - можно сюдаже прикреплять и мы переоткроем и обсудим :)
